module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Welcome',
      items: ['welcome/modules', 'welcome/paths'],
    },
    {
      type: 'category',
      label: 'Blockchain Basics',
      items: ['blockchain-basics/introduction', 'blockchain-basics/exam'],
    },
    {
      type: 'category',
      label: 'Tezos Basics',
      items: [
        'tezos-basics/introduction',
        'tezos-basics/smart-contracts',
        'tezos-basics/liquid-proof-of-stake',
        'tezos-basics/operations',
        'tezos-basics/cli-and-rpc',
        'tezos-basics/governance-on-chain',
        'tezos-basics/history-of-amendements',
        'tezos-basics/economics-and-rewards',
        'tezos-basics/exam',
      ],
    },
    {
      type: 'category',
      label: 'Deploy a node',
      items: ['deploy-a-node/introduction', 'deploy-a-node/exam'],
    },
    {
      type: 'category',
      label: 'How to use an Explorer',
      items: ['explorer/introduction', 'explorer/exam'],
    },
    {
      type: 'category',
      label: 'SmartPy',
      items: ['smartpy/introduction', 'smartpy/exam'],
    },
    {
      type: 'category',
      label: 'LIGO',
      items: [
          'ligo/introduction',
          'ligo/installation',
          'ligo/language-basics',
          'ligo/deploy-a-contract',
          'ligo/unit-testing',
          'ligo/examples',
          'ligo/exam',
          'ligo/take-away',
          'ligo/contracts-ligo',
        ],
    },
    {
      type: 'category',
      label: 'Michelson',
      items: [
        'michelson/introduction',
        'michelson/language-basics',
        'michelson/smart-contracts',
        'michelson/tutorial',
        'michelson/instructions-reference',
        'michelson/examples',
        'michelson/exam',
        'michelson/take-away',
      ],
    },
    {
      type: 'category',
      label: 'Build a Dapp',
      items: ['dapp/introduction',
      'dapp/truffle_compilation_migration'],
    },
    {
      type: 'category',
      label: 'Baking',
      items: ['baking/introduction', 'baking/exam'],
    },
    {
      type: 'category',
      label: 'Deploy Bakers',
      items: ['baker/introduction', 'baker/exam'],
    },
    {
      type: 'category',
      label: 'DeFi',
      items: [
        'defi/introduction',
        'defi/token-standards',
        'defi/dexs',
        'defi/wrapped-assets',
        'defi/cross-chain-swaps',
        'defi/oracles',
        'defi/stablecoins',
        'defi/synthetics',
        'defi/lending',
        'defi/exam',
      ],
    },
    {
      type: 'category',
      label: 'Formal Verification',
      items: ['formal-verification/introduction', 'formal-verification/exam'],
    },
    {
      type: 'category',
      label: 'Private Blockchain',
      items: ['private/introduction', 'private/exam'],
    },
    {
      type: 'category',
      label: 'How to contribute',
      items: [
        'contribute/introduction',
        'contribute/report-issue',
        'contribute/opentezos',
        'contribute/tezos-core',
        'contribute/grant',
        'contribute/baker',
        'contribute/exam',
      ],
    },
  ],
}
